name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set current timestamp as env variable
        id: tagname
        run: echo "::set-output name=timestamp::$(date +'%s')"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - run: npm ci
      - run: npm run format:validate
      - run: npm run --workspaces test:types
      - run: npm run --workspaces test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v3
        env:
          TAG_NAME: ${{ steps.tagname.outputs.timestamp }}
        with:
          push: ${{ github.ref_name == 'main' }}
          file: "Dockerfile.client"
          tags: mstruebing/planning-poker-client:${{ steps.tagname.outputs.timestamp }}

      - name: Build and push server
        uses: docker/build-push-action@v3
        env:
          TAG_NAME: ${{ steps.tagname.outputs.timestamp }}
        with:
          push: ${{ github.ref_name == 'main' }}
          file: "Dockerfile.server"
          tags: mstruebing/planning-poker-server:${{ steps.tagname.outputs.timestamp }}
